version: '3'

services:
   db:
     ports:
       - "8001:3306"
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   web:
     depends_on:
       - db
     build:
       context: .
       dockerfile: Dockerfile
       args:
         woocommerce_version: 4.4.0
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DEBUG: 1
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_CONFIG_EXTRA: |
        define( 'WPLANG', '${WPLANG}');
        define( 'UPLOADS', '/var/www/html/wp-content/uploads' );
        define( 'WP_DEBUG_LOG', '/tmp/wp-errors.log');
        define( 'WP_SITEURL', 'http://' . $$_SERVER['HTTP_HOST']);
        define( 'WP_HOME', 'http://' . $$_SERVER['HTTP_HOST']);
     volumes:
        - .:/var/www/html/wp-content/plugins/komoju-woocommerce
volumes:
    db_data:

# # Uncomment to use with Kaiser
# networks:
#   default:
#     name: kaiser_net
#     external: true
